[bot]
bot = true
token = "XXXXXXXXXXXXXXXXXXXXXXXXX"
guild = "XXXXXXXXXXXXXXXXXXXXXX"
alert_chan = "XXXXXXXXXXXXXXXXXXXXXX"
vocal_chan = "XXXXXXXXXXXXXXXXXXXXXX"
sans_papier = "XXXXXXXXXXXXXXXXXXXXXX"