[bot]
bot = true
token = "XXXXXXXXXXXXXXXXXXXXXXXXX"
guild = "XXXXXXXXXXXXXXXXXXXXXX"

[ping]

    [ping.douane]
        alert_chan = 0
        vocal_chan = 0
        role_ping = [0, 0]
        accepte_role = [0, 0]
        message = ""